version: "3.8"

services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
    networks:
      - jenkins_network

  sonarqube:
    image: sonarqube:latest
    ports:
      - "9000:9000"
    networks:
      - jenkins_network

volumes:
  jenkins_data:

networks:
  jenkins_network:
    driver: bridge

